Repository fscdev/vkwave, pull requests merged in 2020-04, with the labels that each got.

#24 :pencil: Add redis storage example to docs
  docs/bots/storage.md
Labels: documentation, low-priority

#29 Some fixes in bots/utils/uploaders
  docs/bots/utils/uploaders.md
  tests/bots/utils/test_vkwave_bots_utils.py
  vkwave/bots/easy.py
  vkwave/bots/utils/uploaders/__init__.py
  vkwave/bots/utils/uploaders/audio_uploader.py
  vkwave/bots/utils/uploaders/doc_uploader.py
  vkwave/bots/utils/uploaders/photo_uploader.py
  vkwave/bots/utils/uploaders/uploader.py
Labels: bots-utils, help wanted, high-priority

#22 Add Streaming API support
  vkwave/http/__init__.py
  vkwave/http/ws.py
  vkwave/streaming/__init__.py
  vkwave/streaming/client.py
  vkwave/streaming/errors.py
  vkwave/streaming/model.py
Labels: good first issue, low-priority
